version: "1"

execution_config:
  file:
    path: router.json
    watch: true
    watch_interval: "10m"

graph:
  token: ""

dev_mode: true
health_check_path: "/health"
graphql_path: "/graphql"

log_level: "info"

cors:
  allow_origins: ["*"]
  allow_headers: ["*"]
  allow_methods: ["GET", "POST", "OPTIONS"]
