version: "1"

storage_providers:
  s3:
    - id: "s3"
      endpoint: "minio:9000"
      bucket: "cosmo"
      secure: false

execution_config:
  storage:
    provider_id: "s3" # The ID of the storage provider to use
    object_path: "router.json"

shutdown_delay: 15s
grace_period: 20s
poll_interval: 10s

graph:
  token: ""

dev_mode: true
health_check_path: "/health"
graphql_path: "/graphql"

log_level: "info"

cors:
  allow_origins: ["*"]
  allow_headers: ["*"]
  allow_methods: ["GET", "POST", "OPTIONS"]
